### PR TITLE
Fix FormData not being correctly typed

### PR DESCRIPTION
**Pull request by wuyuanyi135**
see #1099.

My fix is a bit hacky. But it generates the correct code. The correct one should be:

1. `useMutation` hook should pass in the `XXXXRequest` object, which will be assembled into FormData in the function.
2. `SchemaType` should generate `request` with the type `XXXXRequest` not `FormData`. (This is the type passed into `useMutation`, which does not take formData but the object)
3. the third type of the client generic should be FormData:

```
const res = await client<FirmwareUpdate["data"], FirmwareUpdate["error"], **FormData**>({
                method: "post",
                url: `/api/devices/firmware_update`,
                params,
                data: formData,
                headers: { "Content-Type": "multipart/form-data", ...clientOptions.headers },
                ...clientOptions
            });
```

### CODE REVIEW

**Comment by wuyuanyi135** [comment]
Comparing generated file 
# Version 2.24.0 (Unmodified)

```typescript
// useFirmwareUpdate.ts
import client from "@kubb/swagger-client/client";
import { useMutation } from "@tanstack/react-query";
import type { FirmwareUpdateMutationResponse, FirmwareUpdateQueryParams, FirmwareUpdate422 } from "../../types/devicesController/FirmwareUpdate";
import type { UseMutationOptions } from "@tanstack/react-query";

 type FirmwareUpdateClient = typeof client<FirmwareUpdateMutationResponse, FirmwareUpdate422, FormData>;
type FirmwareUpdate = {
    data: FirmwareUpdateMutationResponse;
    error: FirmwareUpdate422;
    request: FormData;
    pathParams: never;
    queryParams: FirmwareUpdateQueryParams;
    headerParams: never;
    response: FirmwareUpdateMutationResponse;
    client: {
        parameters: Partial<Parameters<FirmwareUpdateClient>[0]>;
        return: Awaited<ReturnType<FirmwareUpdateClient>>;
    };
};
/**
 * @description 固件升级:param dm::param ip::param fw_file:
 * @summary Firmware Update Api
 * @link /api/devices/firmware_update
 */
export function useFirmwareUpdate(options: {
    mutation?: UseMutationOptions<FirmwareUpdate["response"], FirmwareUpdate["error"], {
        params: FirmwareUpdate["queryParams"];
        data: FirmwareUpdate["request"];
    }>;
    client?: FirmwareUpdate["client"]["parameters"];
} = {}) {
    const { mutation: mutationOptions, client: clientOptions = {} } = options ?? {};
    return useMutation({
        mutationFn: async ({ params, data }) => {
            const formData = new FormData();
            if (data) {
                Object.keys(data).forEach((key) => {
                    const value = data[key];
                    if (typeof key === "string" && (typeof value === "string" || value instanceof Blob)) {
                        formData.append(key, value);
                    }
                });
            }
            const res = await client<FirmwareUpdate["data"], FirmwareUpdate["error"], FirmwareUpdate["request"]>({
                method: "post",
                url: `/api/devices/firmware_update`,
                params,
                data: formData,
                headers: { "Content-Type": "multipart/form-data", ...clientOptions.headers },
                ...clientOptions
            });
            return res.data;
        },
        ...mutationOptions
    });
}
```

# Modified version

```typescript
// useFirmwareUpdate.ts
import client from "@kubb/swagger-client/client";
import { useMutation } from "@tanstack/react-query";
import type { FirmwareUpdateMutationRequest, FirmwareUpdateMutationResponse, FirmwareUpdateQueryParams, FirmwareUpdate422 } from "../../types/devicesController/FirmwareUpdate";
import type { UseMutationOptions } from "@tanstack/react-query";

 type FirmwareUpdateClient = typeof client<FirmwareUpdateMutationResponse, FirmwareUpdate422, FormData>;
type FirmwareUpdate = {
    data: FirmwareUpdateMutationResponse;
    error: FirmwareUpdate422;
    request: FirmwareUpdateMutationRequest;
    pathParams: never;
    queryParams: FirmwareUpdateQueryParams;
    headerParams: never;
    response: FirmwareUpdateMutationResponse;
    client: {
        parameters: Partial<Parameters<FirmwareUpdateClient>[0]>;
        return: Awaited<ReturnType<FirmwareUpdateClient>>;
    };
};
/**
 * @description 固件升级:param dm::param ip::param fw_file:
 * @summary Firmware Update Api
 * @link /api/devices/firmware_update
 */
export function useFirmwareUpdate(options: {
    mutation?: UseMutationOptions<FirmwareUpdate["response"], FirmwareUpdate["error"], {
        params: FirmwareUpdate["queryParams"];
        data: FirmwareUpdate["request"];
    }>;
    client?: FirmwareUpdate["client"]["parameters"];
} = {}) {
    const { mutation: mutationOptions, client: clientOptions = {} } = options ?? {};
    return useMutation({
        mutationFn: async ({ params, data }) => {
            const formData = new FormData();
            if (data) {
                Object.keys(data).forEach((key) => {
                    const value = data[key];
                    if (typeof key === "string" && (typeof value === "string" || value instanceof Blob)) {
                        formData.append(key, value);
                    }
                });
            }
            const res = await client<FirmwareUpdate["data"], FirmwareUpdate["error"], FormData>({
                method: "post",
                url: `/api/devices/firmware_update`,
                params,
                data: formData,
                headers: { "Content-Type": "multipart/form-data", ...clientOptions.headers },
                ...clientOptions
            });
            return res.data;
        },
        ...mutationOptions
    });
}
```

**Comment by stijnvanhulle** [comment]
@all-contributors add @wuyuanyi135 for code

**Review by stijnvanhulle — APPROVED** [review]

**Comment by stijnvanhulle** [comment]
@wuyuanyi135  We are using `changeset` meaning you need to run `pnpm changeset` and follow the steps in the prompt to generate a minor version and push those changes to your branch. Thanks for your contribution :)

**Comment by wuyuanyi135** [comment]
@stijnvanhulle Thanks for reviewing the changes! I am not familiar with the workflows. Would the new commit after running `pnpm changeset` be sufficient?

**Comment by wuyuanyi135** [comment]
@stijnvanhulle Hi. I haven't followed up with this fix. May I ask if this is fix has been scheduled?

**Comment by stijnvanhulle** [comment]
Closing this one because this has been resolved a part of v3 of Kubb

**Pull request closed without merging**
