### PR TITLE
fix: update faker.image.imageUrl to faker.image.url

### PR DESCRIPTION
**Pull request by hkang1**
Looks like the [faker image docs](https://fakerjs.dev/api/image#url) indicate the correct call is `url()` instead of `imageUrl()`?

### CODE REVIEW

**Comment by stijnvanhulle** [comment]
Hmm I was not aware of that, thanks for fixing this.

**Comment by stijnvanhulle** [comment]
@all-contributers add @hkang1 for code

**Comment by stijnvanhulle** [comment]
@all-contributors please add @hkang1 for code

**Comment by hkang1** [comment]
thanks for the speedy response and merging!

**Pull request merged**
